--- 
apiVersion: v1
kind: Service
metadata: 
  name: springbootdemo-mufg
  namespace: mufg
  labels:
    app: springbootdemo-mufg
spec: 
  ports: 
    - 
      name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector: 
    app: springbootdemo-mufg
  type: ClusterIP


---


apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: springbootdemo-mufg-deployment
  namespace: mufg
  labels:
    app: springbootdemo-mufg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdemo-mufg
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springbootdemo-mufg
    spec:
      containers:
      - name: springbootdemo-mufg
        image: registry.hub.docker.com/virtusademo/mufg-java
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP

---

apiVersion:  extensions/v1beta1
kind: Ingress
metadata:
  name: springbootdemo-mufg
  namespace: mufg
  labels:
    app: springbootdemo-mufg
  annotations:
    # zalando.org/skipper-predicate: Source("34.218.139.139/32", "35.163.194.239/32")
spec:
  rules:
    - host: springbootdemo-mufg.apps.xlabsdfs.com
      http:
        paths:
          - path: /
            backend:
              serviceName: springbootdemo-mufg
              servicePort: http
          - path: /*
            backend:
              serviceName: springbootdemo-mufg
              servicePort: http

